 version: '3.1'
 services:
   postgresqldb:
     image: postgres
     ports:
       - "5432:5432"
     environment:
       - POSTGRES_PASSWORD=9999
       - POSTGRES_USER=postgres
       - POSTGRES_DB=dbsenior